/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package zksds;

import org.apache.zookeeper.*;



public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
